### ISSUE TITLE
Safe Zone

### ISSUE THREAD

**Issue by bookerthegeek** [bookerthegeek/Mob-Option-Redux#1]
- Create a safe zone around Spawn in blocks before effects are implamented

**Comment by Matryoshika** [comment]
Base logic was already present in base Mob-Options
Added minor calculation config to use overworld's actual spawn-point vs centered 0,0
https://github.com/bookerthegeek/Mob-Option-Redux/commit/47309bbc149b0ca2d9e2c7dc81bd7733bd191554
