### ISSUE TITLE
Mob Options

### ISSUE THREAD

**Issue by bookerthegeek** [bookerthegeek/Mob-Option-Redux#2]
- [x] Apply to Mobs from other mods
- [x] Blacklist mobs by entity Name
- [x] ~Blacklist mobs by ModID~

**Comment by Matryoshika** [comment]
Already applicable to mobs from other mods. Only need to know the entity's getEntityString name¹
After discussing with @bookerthegeek, MobOptions blacklist/whitelist is only for the ignore-light-level
All hostiles will still get buffed.

¹https://github.com/bookerthegeek/Mob-Option-Redux/commit/fffaf342adefe3c9da8d0e712da8c24ee701a55b
