### ISSUE TITLE
Capability migration

### ISSUE THREAD

**Issue by Matryoshika** [bookerthegeek/Mob-Option-Redux#5]
- [x]  Migrate raw NBT-handling to [Capabilities](https://mcforge.readthedocs.io/en/latest/datastorage/capabilities/).   

- [x] Move Armour, Stats & Enchanting into separate Capabilities (Essentially become modules)
Modularity would also allow defining modded armours etc to be used.

**Comment by Matryoshika** [comment]
Stats

- [x] Health Capability
- [x] Follow Range Capability
- [x] Attack Damage Capability

---
Enchanting

- [x] Equipment Enchanting Capability

---
Equipment

- [x] Armour ~Capability~
- [x] Weapon ~Capability~
_(Not capability, as data is saved as JSON)_

_Offhand equipment as well? (Shields etc)_ @bookerthegeek 
Doing these "artifacts" first, before tackling #4

**Comment by bookerthegeek** [comment]
Actually yes please also the offhand.

**Comment by Matryoshika** [comment]
@bookerthegeek 
Going to make a .JSON config file just for the possible equipment that a mob can spawn with.

Going to keep the 5-tier system, but each tier will contain "sets" of armour & weapons. Each tier's sets should thus be kept at approximately the same strength etc (iron, thaumium, manasteel etc)
Should also be easy to add per-type-sets, so Zombies can get from the general sets, and from Zombie-only sets for example.

Tried raw Forge-Config, but gets messy when you have to dictate slot:domain:name:meta (Feet:minecraft:diamond_leggings:0 for example) and even worse with weapons.

**Comment by Matryoshika** [comment]
@bookerthegeek 
Just a heads up. Mobs will be randomly given 1 equipment set, when spawned. The tier (1->5) is the same as before, but each tier can as mentioned contain several different types of equipment.
The mob will not get 1 part from this set, and 1 part of that set, but kept to the one given.
You can of course create "chimera" sets in the JSON file, so they are not forced to wear [full manasteel] etc

Here's what I think we could ship as default JSON
https://gist.github.com/Matryoshika/fdca03ff6a19a41606cc4c08627f2e2d
Notice how Tier1 got 2 "leather" sets, with different weapons. A mob can get one of these, if he gets assigned to tier1 equipment.

Because mobs spawn well after mods have added their items, it already has built-in support for adding modded items. Just get the RegistryName for an item (domain:name, like minecraft:bow etc)

**Comment by bookerthegeek** [comment]
Looks good. That will work better than lists of equipment per tier.

**Comment by Matryoshika** [comment]
Stats moved to Capabilities
Equipment & Enchantment logic changed to allow much greater customization.
Closing issue as solved.
